parameters:
#    ea_git_hub_api_search.example.class: EA\GitHubAPISearchBundle\Example

services:
#    ea_git_hub_api_search.example:
#        class: %ea_git_hub_api_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
