_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

_security:
    resource: "@EASecurityBundle/Resources/config/routing.yml"

ea_git_hub_api_search:
    resource: "@EAGitHubAPISearchBundle/Resources/config/routing.yml"
    prefix:   /

github_query:
    pattern:  /search/query/{username}
    defaults: { _controller: EAGitHubAPISearchBundle:Default:search, username: '' }
    requirements:
        _method:  GET